# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clovaspeech.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'clovaspeech.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63lovaspeech.proto\x12\x18ncloud.ai.clovaspeech.v1\"\x81\x01\n\x12RecognitionRequest\x12=\n\x06\x63onfig\x18\x01 \x01(\x0b\x32+.ncloud.ai.clovaspeech.v1.RecognitionConfigH\x00\x12\x17\n\raudio_content\x18\x02 \x01(\x0cH\x00\x42\x13\n\x11streaming_request\"\xa2\x01\n\x13RecognitionResponse\x12\x43\n\x06result\x18\x01 \x01(\x0b\x32\x31.ncloud.ai.clovaspeech.v1.SpeechRecognitionResultH\x00\x12\x30\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1f.ncloud.ai.clovaspeech.v1.ErrorH\x00\x42\x14\n\x12streaming_response\"\x95\x02\n\x11RecognitionConfig\x12\x10\n\x08language\x18\x01 \x01(\t\x12K\n\x08\x65ncoding\x18\x02 \x01(\x0e\x32\x39.ncloud.ai.clovaspeech.v1.RecognitionConfig.AudioEncoding\x12\x19\n\x11sample_rate_hertz\x18\x03 \x01(\x05\x12\x16\n\x0eword_alignment\x18\x06 \x01(\x08\x12\x11\n\tfull_text\x18\n \x01(\x08\"[\n\rAudioEncoding\x12\x18\n\x14\x45NCODING_UNSPECIFIED\x10\x00\x12\x0c\n\x08LINEAR16\x10\x01\x12\x07\n\x03PCM\x10\x01\x12\x0c\n\x08OGG_OPUS\x10\x06\x12\x07\n\x03MP3\x10\x08\x1a\x02\x10\x01\"\\\n\x17SpeechRecognitionResult\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x03\x12\r\n\x05\x66inal\x18\x04 \x01(\x08\"&\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\x85\x01\n\x15\x43lovaSpeechRecognizer\x12l\n\tRecognize\x12,.ncloud.ai.clovaspeech.v1.RecognitionRequest\x1a-.ncloud.ai.clovaspeech.v1.RecognitionResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clovaspeech_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOGNITIONCONFIG_AUDIOENCODING']._loaded_options = None
  _globals['_RECOGNITIONCONFIG_AUDIOENCODING']._serialized_options = b'\020\001'
  _globals['_RECOGNITIONREQUEST']._serialized_start=48
  _globals['_RECOGNITIONREQUEST']._serialized_end=177
  _globals['_RECOGNITIONRESPONSE']._serialized_start=180
  _globals['_RECOGNITIONRESPONSE']._serialized_end=342
  _globals['_RECOGNITIONCONFIG']._serialized_start=345
  _globals['_RECOGNITIONCONFIG']._serialized_end=622
  _globals['_RECOGNITIONCONFIG_AUDIOENCODING']._serialized_start=531
  _globals['_RECOGNITIONCONFIG_AUDIOENCODING']._serialized_end=622
  _globals['_SPEECHRECOGNITIONRESULT']._serialized_start=624
  _globals['_SPEECHRECOGNITIONRESULT']._serialized_end=716
  _globals['_ERROR']._serialized_start=718
  _globals['_ERROR']._serialized_end=756
  _globals['_CLOVASPEECHRECOGNIZER']._serialized_start=759
  _globals['_CLOVASPEECHRECOGNIZER']._serialized_end=892
# @@protoc_insertion_point(module_scope)
